sudo: required

services:
- docker

archlinux:
  repos:
  - archlinuxfr=http://repo.archlinux.fr/$arch
  packages:
  - p7zip
  - wine
  - wine-mono
  - wine_gecko
  - xorg-xwininfo
  - wqy-microhei
  - adobe-source-han-sans-cn-fonts
  script:
  - "makepkg"

script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key: $GH_TOKEN
  file_glob: true
  file:
    - "deepin-wine-thunderspeed-*-x86_64.pkg.tar.xz"
  on:
    tags: true
    all_branches: true
    repo: countstarlight/deepin-wine-thunderspeed-arch
